### ISSUE TITLE
为什么不能下载了呢？提示我下载的大小受到限制

### ISSUE THREAD

**Issue by JobsMeng** [ihmily/QuarkPanTool#16]
``python quark.py
╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                     _                                  _                     _       ║    
║       __ _   _   _    __ _   _ __  | | __    _ __     __ _   _ __     | |_    ___     ___   | |      ║
║      / _  | | | | |  / _  | | '__| | |/ /   | '_ \   / _  | |  _ \    | __|  / _ \   / _ \  | |      ║
║     | (_| | | |_| | | (_| | | |    |   <    | |_) | | (_| | | | | |   | |_  | (_) | | (_) | | |      ║
║      \__, |  \__,_|  \__,_| |_|    |_|\_\   | .__/   \__,_| |_| |_|    \__|  \___/   \___/  |_|      ║
║         |_|                                 |_|                                                      ║
║                                                                                                      ║
║                                  Author: Hmily  Version: 0.0.3                                       ║
║                          GitHub: https://github.com/ihmily/QuarkPanTool                              ║
╠══════════════════════════════════════════════════════════════════════════════════════════════════════╣
║     1.分享地址转存文件   2.批量生成分享链接   3.切换网盘保存目录   4.创建网盘文件夹   5.下载到本地   6.登录        ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝
[2024-10-20 22:42:06] 用户名：林克3237
[2024-10-20 22:42:06] 你当前选择的网盘保存目录: 根目录 文件夹
请输入你的选择(1—6或q退出)：5
输入你的选择(1单个地址下载，2批量下载):2
[2024-10-20 22:42:14] 文件分享链接：https://pan.quark.cn/s/bfe537c3a9b9
[2024-10-20 22:42:14] 转存总数：1，文件数：1，文件夹数：0 | 支持嵌套
[2024-10-20 22:42:14] 文件转存列表：['01.mp4']
[2024-10-20 22:42:14] 文件夹转存列表：[]
[2024-10-20 22:42:14] 文件下载地址列表获取失败, download file size limit[2323b62bd86742639eccb1bd346ce0b9]``

**Comment by JobsMeng** [comment]
这是为什么呢？只要我用的不是官方的手段，我就一定会被限制下载文件的大小吗？

**Comment by ihmily** [comment]
@JobsMeng 官方文件下载大小限制已解决，目前不限下载文件大小
