### ISSUE TITLE
上述出现中文乱码，怎么办？

### ISSUE THREAD

**Issue by shluqu-a** [ihmily/QuarkPanTool#3]
上述出现中文乱码，怎么办？

**Comment by shluqu-a** [comment]
![Uploading 屏幕截图 2024-05-04 123104.png…]()

**Comment by shluqu-a** [comment]
![屏幕截图 2024-05-04 123104](https://github.com/ihmily/QuarkPanTool/assets/84126383/3c2f28da-51d5-4dcd-a394-b58be8acaa68)

**Comment by ihmily** [comment]
Windows 控制台默认编码问题  自行Google
