### ISSUE TITLE
在linux服务端可以用这个吗

### ISSUE THREAD

**Issue by jenchih** [ihmily/QuarkPanTool#7]
我想要在cli下，下载夸克的文件， 现在卡在cookie那边，不知道需要那些cookie

**Comment by ihmily** [comment]
> 我想要在cli下，下载夸克的文件， 现在卡在cookie那边，不知道需要那些cookie

自己在网页登录夸克后，获取文件列表页面Cookie，手动填写到config/cookies.txt文件中即可。不过由于夸克网页端的下载限制，脚本中的下载只支持小文件，貌似超过100M就不行了。
